from enum import Enum


class ArtiAttrType(Enum):
    WATER_SUB_HURT = "FIGHT_PROP_WATER_SUB_HURT"
    HP_PERCENT = "FIGHT_PROP_HP_PERCENT"
    HEAL_ADD = "FIGHT_PROP_HEAL_ADD"
    ICE_SUB_HURT = "FIGHT_PROP_ICE_SUB_HURT"
    DEFENSE = "FIGHT_PROP_DEFENSE"
    GRASS_SUB_HURT = "FIGHT_PROP_GRASS_SUB_HURT"
    FIRE_SUB_HURT = "FIGHT_PROP_FIRE_SUB_HURT"
    ATTACK_PERCENT = "FIGHT_PROP_ATTACK_PERCENT"
    CRITICAL = "FIGHT_PROP_CRITICAL"
    WIND_ADD_HURT = "FIGHT_PROP_WIND_ADD_HURT"
    DEFENSE_PERCENT = "FIGHT_PROP_DEFENSE_PERCENT"
    ROCK_ADD_HURT = "FIGHT_PROP_ROCK_ADD_HURT"
    WATER_ADD_HURT = "FIGHT_PROP_WATER_ADD_HURT"
    ATTACK = "FIGHT_PROP_ATTACK"
    ROCK_SUB_HURT = "FIGHT_PROP_ROCK_SUB_HURT"
    PHYSICAL_ADD_HURT = "FIGHT_PROP_PHYSICAL_ADD_HURT"
    ELEC_SUB_HURT = "FIGHT_PROP_ELEC_SUB_HURT"
    CRITICAL_HURT = "FIGHT_PROP_CRITICAL_HURT"
    FIRE_ADD_HURT = "FIGHT_PROP_FIRE_ADD_HURT"
    ELEC_ADD_HURT = "FIGHT_PROP_ELEC_ADD_HURT"
    ICE_ADD_HURT = "FIGHT_PROP_ICE_ADD_HURT"
    GRASS_ADD_HURT = "FIGHT_PROP_GRASS_ADD_HURT"
    CHARGE_EFFICIENCY = "FIGHT_PROP_CHARGE_EFFICIENCY"
    WIND_SUB_HURT = "FIGHT_PROP_WIND_SUB_HURT"
    ELEMENT_MASTERY = "FIGHT_PROP_ELEMENT_MASTERY"
    HP = "FIGHT_PROP_HP"


class BodyType(Enum):
    BODY_MALE = "BODY_MALE"
    AVATAR_LOLI = "AVATAR_LOLI"
    NPC_MALE = "NPC_MALE"
    BODY_GIRL = "BODY_GIRL"
    BODY_LOLI = "BODY_LOLI"
    NPC_FEMALE = "NPC_FEMALE"
    NPC_MUSCLEMAN = "NPC_MUSCLEMAN"
    NPC_ELDER = "NPC_ELDER"
    AVATAR_GIRL = "AVATAR_GIRL"
    AVATAR_MALE = "AVATAR_MALE"
    NPC_CHILD = "NPC_CHILD"
    AVATAR_BOY = "AVATAR_BOY"
    BODY_LADY = "BODY_LADY"
    AVATAR_LADY = "AVATAR_LADY"
    BODY_BOY = "BODY_BOY"


class WeaponType(Enum):
    POLE = "WEAPON_POLE"
    BOW = "WEAPON_BOW"
    CLAYMORE = "WEAPON_CLAYMORE"
    CATALYST = "WEAPON_CATALYST"
    SWORD = "WEAPON_SWORD_ONE_HAND"


class UseType(Enum):
    ABANDON = "AVATAR_ABANDON"
    SYNC_TEST = "AVATAR_SYNC_TEST"
    FORMAL = "AVATAR_FORMAL"


class QualityType(Enum):
    PURPLE = "QUALITY_PURPLE"
    ORANGE = "QUALITY_ORANGE"
    BLUE = "QUALITY_BLUE"


class IdentityType(Enum):
    NORMAL = "AVATAR_IDENTITY_NORMAL"


class ElementType(Enum):
    ANEMO = "Wind"
    ELECTRO = "Electric"
    PYRO = "Fire"
    CRYO = "Ice"
    GEO = "Rock"
    HYDRO = "Water"
