from enum import Enum


class ItemType(Enum):
    ARTIFACT = "ITEM_RELIQUARY"
    VIRTUAL = "ITEM_VIRTUAL"
    MATERIAL = "ITEM_MATERIAL"
    WEAPON = "ITEM_WEAPON"
    DISPLAY = "ITEM_DISPLAY"


class FoodQuality(Enum):
    STRANGE = "FOOD_QUALITY_STRANGE"
    DELICIOUS = "FOOD_QUALITY_DELICIOUS"
    ORDINARY = "FOOD_QUALITY_ORDINARY"


class MaterialType(Enum):
    ADSORBATE = "MATERIAL_ADSORBATE"
    FLYCLOAK = "MATERIAL_FLYCLOAK"
    NOTICE_ADD_HP = "MATERIAL_NOTICE_ADD_HP"
    CHEST_BATCH_USE = "MATERIAL_CHEST_BATCH_USE"
    FAKE_ABSORBATE = "MATERIAL_FAKE_ABSORBATE"
    FOOD = "MATERIAL_FOOD"
    AVATAR = "MATERIAL_AVATAR"
    QUEST = "MATERIAL_QUEST"
    SELECTABLE_CHEST = "MATERIAL_SELECTABLE_CHEST"
    EXCHANGE = "MATERIAL_EXCHANGE"
    CHEST = "MATERIAL_CHEST"
    SEA_LAMP = "MATERIAL_SEA_LAMP"
    EXP_FRUIT = "MATERIAL_EXP_FRUIT"
    CRICKET = "MATERIAL_CRICKET"
    WIDGET = "MATERIAL_WIDGET"
    TALENT = "MATERIAL_TALENT"
    ELEM_CRYSTAL = "MATERIAL_ELEM_CRYSTAL"
    NAMECARD = "MATERIAL_NAMECARD"
    AVATAR_MATERIAL = "MATERIAL_AVATAR_MATERIAL"
    CONSUME = "MATERIAL_CONSUME"
    WEAPON_EXP_STONE = "MATERIAL_WEAPON_EXP_STONE"
