from enum import Enum


class UseTarget(Enum):
    AVATAR = "ITEM_USE_TARGET_SPECIFY_AVATAR"
    DEAD_AVATAR = "ITEM_USE_TARGET_SPECIFY_DEAD_AVATAR"
    ALIVE_AVATAR = "ITEM_USE_TARGET_SPECIFY_ALIVE_AVATAR"
    TEAM = "ITEM_USE_TARGET_CUR_TEAM"


class EquipPart(Enum):
    GOBLET = "EQUIP_RING"
    FEATHER = "EQUIP_NECKLACE"
    SANDS = "EQUIP_SHOES"
    CIRCLET = "EQUIP_DRESS"
    FLOWER = "EQUIP_BRACER"
